<?php
    /*
    * Project:     Clan Stat
    * License:     Creative Commons - Attribution-Noncommercial-Share Alike 3.0 Unported
    * Link:        http://creativecommons.org/licenses/by-nc-sa/3.0/
    * -----------------------------------------------------------------------
    * Began:       2011
    * Date:        $Date: 2011-10-20 00:00:00 +0200 $
    * -----------------------------------------------------------------------
    * @author      $Author: Edd, Exinaus, SHW  $
    * @copyright   2011-2013 Edd - Aleksandr Ustinov
    * @link        http://wot-news.com
    * @package     Clan Stat
    * @version     $Rev: 3.2.3 $
		* @translation [sk] relic242
    *
    */

    $lang['loading']  = 'Nalaganje';
    $lang['language'] = 'sk';
    $lang['total_p'] = 'Spolu hráčov';
    $lang['games_p'] = 'Spolu bitiek'; 
    $lang['all_battles'] = $lang['clan_battles'] = $lang['company_battles'] ='Bitiek';
    $lang['all_wins'] = $lang['clan_wins'] = $lang['company_wins'] = 'Výhry';
    $lang['all_losses'] = $lang['clan_losses'] = $lang['company_losses'] = 'Prehry';
    $lang['all_draws'] = $lang['clan_draws'] = $lang['company_draws'] = 'Remízy';
    $lang['all_survived_battles'] = $lang['clan_survived_battles'] = $lang['company_survived_battles'] =  'Prežití';
    $lang['all_frags'] = $lang['clan_frags'] = $lang['company_frags'] = 'Zničených';
    $lang['all_spotted'] = $lang['clan_spotted'] = $lang['company_spotted'] = 'Odhalených';
    $lang['all_damage_dealt'] = $lang['clan_damage_dealt'] = $lang['company_damage_dealt'] = 'Poškodenie';
    $lang['all_capture_points'] = $lang['clan_capture_points'] = $lang['company_capture_points'] = 'Obsadenie';
    $lang['all_dropped_capture_points'] = $lang['clan_dropped_capture_points'] = $lang['company_dropped_capture_points'] = 'Obrana';
    $lang['all_xp'] = $lang['clan_xp'] = $lang['company_xp'] = 'Spolu skúseností';
    $lang['all_battle_avg_xp'] = $lang['clan_battle_avg_xp'] = $lang['company_battle_avg_xp'] = 'Priemer skúseností';
    $lang['all_damage_received'] = $lang['clan_damage_received'] = $lang['company_damage_received'] ='Obdržané';
    $lang['all_hits_percents'] = $lang['clan_hits_percents'] = $lang['company_hits_percents'] = '% zásahov';
    $lang['max_xp'] = 'Maximum skúseností';
    $lang['page_title'] = 'Bojová efektivita klanu';
    $lang['winp'] = 'Víťazstiev %';
    $lang['gr_p'] = 'Pozícia v rebríčku globálna efektivita';
    $lang['wb_p'] = 'Pozícia v rebríčku výhier/bitiek';
    $lang['eb_p'] = 'Pozícia v rebríčku priemer skúseností na bitku';
    $lang['win_p'] = 'Pozícia v rebríčku víťazstiev';
    $lang['gpl_p'] = 'Pozícia v rebríčku počet bitiek';
    $lang['cpt_p'] = 'Pozícia v rebríčku bodov obsadenia';
    $lang['dmg_p'] = 'Pozícia v rebríčku poškodenia';
    $lang['dpt_p'] = 'Pozícia v rebríčku bodov obrany';
    $lang['frg_p'] = 'Pozícia v rebríčku počet zničených vozidiel';
    $lang['spt_p'] = 'Pozícia v rebríčku počet odhalených vozidiel';
    $lang['exp_p'] = 'Pozícia v rebríčku celkové skúsenosti';
    $lang['gr_v'] = 'Hodnota v rebríčku globálna efektivita';
    $lang['wb_v'] = 'Hodnota v rebríčku výhier/bitiek';
    $lang['eb_v'] = 'Hodnota v rebríčku priemer skúseností na bitku';
    $lang['win_v'] = 'Hodnota v rebríčku víťazstiev';
    $lang['gpl_v'] = 'Hodnota v rebríčku počet bitiek';
    $lang['cpt_v'] = 'Hodnota v rebríčku bodov obsadenia';
    $lang['dmg_v'] = 'Hodnota v rebríčku poškodenia';
    $lang['dpt_v'] = 'Hodnota v rebríčku bodov obrany';
    $lang['frg_v'] = 'Hodnota v rebríčku počet zničených vozidiel';
    $lang['spt_v'] = 'Hodnota v rebríčku počet odhalených vozidiel';
    $lang['exp_v'] = 'Hodnota v rebríčku celkové skúsenosti';
//checked use until here
    $lang['clan'] = 'Člen klanu';
    $lang['overall_title'] = 'Celkové výsledky';
    $lang['perform_title'] = 'Bojové výsledky';
    $lang['avarage_des'] = 'Priemer zničených vozidiel na bitku';
    $lang['avarage_spo'] = 'Priemer odhalených vozidiel na bitku';
    $lang['avarage_dem'] = 'Priemer poškodenia na bitku';
    $lang['avarage_cap'] = 'Priemer bodov obsadenia na bitku';
    $lang['avarage_def'] = 'Priemer bodov obrany na bitku';
    $lang['battel_title'] = 'Bojové skúsenosti';
    $lang['diff'] = 'Rozdiel';
    $lang['rating_title'] = 'Rebríčky';
    $lang['value'] = 'Hodnota';
    $lang['place'] = 'Miesto';
    $lang['tank'] = 'Vozidiel';
    $lang['spg'] = 'delostrelectvo';
    $lang['battle'] = 'Bitiek';
    $lang['lose'] = 'Prehier';
    $lang['dem'] = 'Poškodenie';
    $lang['des'] = 'Zničených';
    $lang['spo'] = 'Odhalených';
    $lang['cap'] = 'Bodov obsadenia';
    $lang['def'] = 'Bodov obrany';
    $lang['roster'] = 'Členov klanu';
    $lang['poss'] = 'Obsadené územia';
    $lang['attack'] = 'Plánované útoky';
    $lang['name'] = 'Meno';
    $lang['in_clan'] = 'V klane od';
    $lang['day_clan'] = 'Dní v klane';
    $lang['role'] = 'Pozícia';
    $lang['error_1'] = "Nemôžem nahrať tento modul. Asi je problém s wargaming.net stránkou";
    $lang['error_2'] = "Nemôžem nahrať tento modul. Asi je problém s wargaming.net stránkou";
    $lang['error_3'] = "Nemôžem nahrať tento modul. Asi je problém s wargaming.net stránkou"; 
    $lang['type'] = 'Typ';
    $lang['title_name'] = 'Meno';
    $lang['map'] = 'Mapa';
    $lang['prime_time'] = 'Hlavný čas';
    $lang['income'] = 'Príjem';
    $lang['owned'] = 'Doba vlastnenia';
    $lang['time'] = 'Čas';
    $lang['province'] = 'Územie';
    $lang['total_gold'] = 'Príjem spolu';
    $lang['damage_short'] = 'Poškodenie';
    $lang['mdmg'] = 'Priemer - poškodenie';
    $lang['mspo'] = 'Priemer - odhalenie';
    $lang['mcap'] = 'Priemer - obsadenie';
    $lang['mdef'] = 'Priemer - obrana';
    $lang['average_perform_title'] = 'Priemerné výsledky';
    $lang['gk_blocked'] = 'Zamknuté vozidlá';
    $lang['version'] = 'verzia';
    $lang['ex_time'] = 'Doba spustenia';
    $lang['sec'] = 'sekúnd';
    $lang['memory'] = 'Použitej pamäte';
    $lang['mb'] = 'mb';
    $lang['error_no_veh'] = 'Toto vozidlo neexistuje';
    $lang['medal_max'] = 'Najlepšia séria, potrebuješ získať 20';
    $lang['medal_max2'] = 'Najlepšia séria, potrebuješ získať 5';
    $lang['medal_class'] = 'trieda';
    $lang['medal_class2'] = 'trieda';
    $lang['medal_amount'] = 'počet';
    $lang['medal_ps'] = 'Pre viac informácií o vyznamenaní prejdi myšou nad jeho názvom';
    $lang['medal_battle'] = 'Počet bitiek na získanie vyznamenania';
    $lang['achiv'] = 'Úspechy';

    $lang['logout'] = 'Odhlásiť';
    $lang['login'] = 'Prihlásiť';
    $lang['hi'] = 'Ahoj';
    $lang['index_loading'] = 'Prosím čakať, nahrávam údaje, môže to chvíľu trvať...(cca 1 minútu)';
    $lang['cron_done'] = 'Úloha dokončená';
    $lang['loosed_today'] = 'Opustenie klanu';
    $lang['new_tanks'] = 'Nové tanky';
    $lang['new_players'] = 'Nový hráči v klane';
    $lang['noone'] = 'Žiadny';
    $lang['players_best_results'] = 'Najlepšie výsledky';
    $lang['players_best_medals'] = 'Najlepšie dosiahnuté vyznamenania';
    $lang['all_types'] = 'Všetky typy';
    $lang['all_lvls'] = 'Všetky úrovne/tiery';
    $lang['select_tanks'] = 'Označ vozidlá na zobrazenie:';
    $lang['select_show'] = 'Zobraziť';
    $lang['select_restriciton'] = 'Nemôžeš označiť všetko! \r\n Nepýtaj sa prečo.';
    $lang['select_medals'] = 'Označ vyznamenania na zobrazenie:';
    $lang['show_full_perform'] = 'Zobraz celkové bojové výsledky';
    $lang['show_average_perform'] = 'Zobraz priemerné bojové výsledky';
    $lang['show_ratingplace'] = 'Zobraz umiestnenie';
    $lang['show_ratingvalue'] = 'Zobraz hodnoty';
    $lang['gotoadmin'] = 'Nastavenia';
    $lang['alltanks_choise_tank'] = 'Výber zobrazených vozidiel:';
    $lang['alltanks_all'] = 'Všetky';
    $lang['germany'] = 'Nemecko';
    $lang['usa'] = 'Usa';
    $lang['china'] = 'Čína';
    $lang['ussr'] = 'Rusko';
    $lang['czech'] = 'Československo';
    $lang['france'] = 'Francúzsko';
    $lang['uk'] = 'Anglicko';
    $lang['japan'] = 'Japonsko';
    $lang['AT-SPG'] = 'TD';
    $lang['SPG'] = 'SPG';
    $lang['lightTank'] = 'LT';
    $lang['mediumTank'] = 'MT';
    $lang['heavyTank'] = 'HT';
    $lang['tab_del'] = 'Modul <b>%1$s</b> (súbor: <b>%2$s</b>) bol vymazaný, ale údaje sú v databáze. <br /> Prosím, vymaž údaje z databázy v Administračnom centre, alebo obnov súbor.';
    $lang['days'] = ' dní';   
    $lang['no_province'] = 'Klan nedrží žiadne územia na Globálnej mape.';
    $lang['no_war'] = 'Klan nemá plánované žiadne bitky na Globálnej mape.';
    $lang['dateof'] = 'Údaje z';
    $lang['reg'] = 'Dátum registrácie:';
    $lang['recruit'] = 'Rekrút';
    $lang['private'] = 'Vojak';
    $lang['recruiter'] = 'Náborár';
    $lang['diplomat'] = 'Diplomat';
    $lang['commander'] = 'Veliteľ';
    $lang['leader'] = 'Vodca'; 
    $lang['vice_leader'] = 'Zástupca';
    $lang['treasurer'] = 'Pokladník';
    $lang['err_med1'] = 'Vyznamenania, ktoré patria hráčom, ktorí opustili klan';
    $lang['err_med2'] = 'Žiadne získané vyznamenania';
    $lang['greeting_top'] = 'Najlepší ';
    $lang['greeting_top1'] = ' eff';
		$lang['greeting_top11'] = ' wn7';
    $lang['greeting_top2'] = ' poškodenie';
    $lang['greeting_top3'] = ' odhalenie';
    $lang['greeting_top4'] = ' obsadenie';
    $lang['greeting_top5'] = ' obrana';
    $lang['greeting_h1'] = 'Celkové výsledky klanu';
    $lang['greeting_h2'] = 'Bojové výsledky klanu';
    $lang['greeting_h3'] = 'Klanové skúsenosti';
    $lang['greeting_sub1'] = '24h';
    $lang['greeting_sub2'] = 'Všetky';
    $lang['averag_hit_ratio'] = 'Streľba';
    $lang['averag_surv'] = 'Prežití';
    $lang['no_new'] = 'Žiadne nové vozidlá';
    $lang['table_resized'] = 'Tabuľka je príliš široká a zobrazuje sa po častiach. Ak chceš vidieť skryté časti, posuň sa smerom na spodok tabuľky.';
    $lang['st_title'] = 'Štatistiky hráčov';
    $lang['classVf'] = 'Špičkový hráč <br>(lepší ako 99,9 % hráčov)';
    $lang['classMf'] = 'Veľmi dobrý hráč <br>(lepší ako 99 % hráčov)';
    $lang['class1f'] = 'Dobrý hráč <br>(lepší ako 90 % hráčov)';
    $lang['class2f'] = 'Priemerný hráč <br>(60 % hráčov)';
    $lang['class3f'] = 'Podpriemerný hráč <br>(lepší ako 45% hráčov)';
    $lang['deer3f'] = 'Slabý hráč <br>(lepší ako 30% hráčov)';
    $lang['deer2f'] = 'Zlý hráč <br>(lepší ako 20% hráčov)';
    $lang['deer1f'] = 'Veľmi zlý hráč <br>(lepší ako 10% hráčov)';
    $lang['deerMf'] = 'Totálna lama <br>(menej ako 10 % hráčov)';
    $lang['emem'] = 'Štýl boja';
    $lang['emem_fsb_title'] = 'Pomer detekovaných a zničených vozidiel voči počtu bitiek';
    $lang['emem_fsb'] = 'Celková agresivita';
    $lang['emem_fb_title'] = 'Pomer zničených vozidiel voči počtu bitiek';
    $lang['emem_fb'] = 'Bojovník';
    $lang['emem_sb_title'] = 'Pomer odhalených vozidiel voči počtu bitiek';
    $lang['emem_sb'] = 'Skaut';
    $lang['emem_cb_title'] = 'Pomer obsadenia voči počtu bitiek';
    $lang['emem_cb'] = 'Nájazdník';
    $lang['emem_db_title'] = 'Pomer obrany voči počtu bitiek';
    $lang['emem_db'] = 'Obránca';
    $lang['brone_anno'] = 'Toto hodnotenie nepreukazuje jasné hranice.';
    $lang['upd_at'] = 'Štatistika aktualizovaná';
    $lang['perform_class'] = ' zoradenie podľa triedy';
    $lang['perform_nation'] = ' zoradenie podľa národností';
    $lang['perform_lvl'] = ' zoradenie podľa úrovne/tieru';
    $lang['duckandcover'] = 'História klanu';
    $lang['till_today'] = 'doteraz';
    $lang['unknown'] = 'Neznáme';
    $lang['med_title'] = 'Dosiahnuté ocenenia';
    $lang['teh_title'] = 'Štatistika vozidiel';
    $lang['lvl_up1'] = 'Pre ';
    $lang['lvl_up2'] = '<br>Na súčastnej úrovni hry to zaberie približne ';
    $lang['lvl_b'] = " bitiek.";
    $lang['lvl_kay'] = " na Kayovu medailu potrebuješ získať ";
    $lang['lvl_heroes'] = " bojových ocenení'.";
    $lang['lvl_car'] = " na Cariusovu medailu potrebuješ zničiť";
    $lang['lvl_des'] = " vozidiel protivníka.";
    $lang['lvl_lac'] = " na Leclercovu medailu potrebuješ získať ";
    $lang['lvl_cap'] = " bodov obsadzovania.";
    $lang['lvl_abr'] = " na Abramsovu medailu potrebuješ vyhrať a prežiť ";
    $lang['lvl_ali'] = " bitiek.";
    $lang['lvl_pop'] = " na Popelovu medailu potrebuješ odhaliť ";
    $lang['lvl_spo'] = " vozidiel protivníka.";
    $lang['lvl_lav'] = " na Lavrinenkovu medailu potrebuješ získať ";
    $lang['lvl_def'] = " bodov obrany.";
    $lang['lvl_kni'] = " na Knispel medailu potrebuješ nastrielať ";
    $lang['lvl_dd'] = " hp poškodenia";
    $lang['class'] = 'Trieda';
    $lang['nation'] = 'Národnosť';
    $lang['level'] = 'Úroveň/tier';
    $lang['teh_anno'] = '*V tabuľke sa zobrazujú vozidlá s viac ako 20 bitkami.';
    $lang['avr_eff_ret'] = 'Priemerná EFF';
    $lang['company'] = 'Jednotka';

    $lang['turns'] = 'turns';  
    $lang['max_lvl'] = 'max lvl';    
?>